/**
 * Fatture in Cloud API v2 - API Reference
 * Connect your software with Fatture in Cloud, the invoicing platform chosen by more than 500.000 businesses in Italy.   The Fatture in Cloud API is based on REST, and makes possible to interact with the user related data prior authorization via OAuth2 protocol.
 *
 * The version of the OpenAPI document: 2.1.8
 * Contact: info@fattureincloud.it
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient'
import PaymentAccount from './PaymentAccount'
import PendingReceivedDocumentPaymentsListItemPaymentTerms from './PendingReceivedDocumentPaymentsListItemPaymentTerms'

/**
 * The PendingReceivedDocumentPaymentsListItem model module.
 * @module model/PendingReceivedDocumentPaymentsListItem
 * @version 2.1.3
 */
class PendingReceivedDocumentPaymentsListItem {
  /**
     * Constructs a new <code>PendingReceivedDocumentPaymentsListItem</code>.
     * @alias module:model/PendingReceivedDocumentPaymentsListItem
     */
  constructor () {
    PendingReceivedDocumentPaymentsListItem.initialize(this)
  }

  /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
  static initialize (obj) {
  }

  /**
     * Constructs a <code>PendingReceivedDocumentPaymentsListItem</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PendingReceivedDocumentPaymentsListItem} obj Optional instance to populate.
     * @return {module:model/PendingReceivedDocumentPaymentsListItem} The populated <code>PendingReceivedDocumentPaymentsListItem</code> instance.
     */
  static constructFromObject (data, obj) {
    if (data) {
      obj = obj || new PendingReceivedDocumentPaymentsListItem()

      if (data.hasOwnProperty('amount')) {
        obj.amount = ApiClient.convertToType(data.amount, 'Number')
      }
      if (data.hasOwnProperty('due_date')) {
        obj.due_date = ApiClient.convertToType(data.due_date, 'Date')
      }
      if (data.hasOwnProperty('paid_date')) {
        obj.paid_date = ApiClient.convertToType(data.paid_date, 'Date')
      }
      if (data.hasOwnProperty('payment_terms')) {
        obj.payment_terms = PendingReceivedDocumentPaymentsListItemPaymentTerms.constructFromObject(data.payment_terms)
      }
      if (data.hasOwnProperty('status')) {
        obj.status = ApiClient.convertToType(data.status, 'String')
      }
      if (data.hasOwnProperty('paid_with_ts_pay')) {
        obj.paid_with_ts_pay = ApiClient.convertToType(data.paid_with_ts_pay, 'Boolean')
      }
      if (data.hasOwnProperty('payment_account')) {
        obj.payment_account = PaymentAccount.constructFromObject(data.payment_account)
      }
    }
    return obj
  }

  /**
     * Validates the JSON data with respect to <code>PendingReceivedDocumentPaymentsListItem</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PendingReceivedDocumentPaymentsListItem</code>.
     */
  static validateJSON (data) {
    // validate the optional field `payment_terms`
    if (data.payment_terms) { // data not null
      PendingReceivedDocumentPaymentsListItemPaymentTerms.validateJSON(data.payment_terms)
    }
    // ensure the json data is a string
    if (data.status && !(typeof data.status === 'string' || data.status instanceof String)) {
      throw new Error('Expected the field `status` to be a primitive type in the JSON string but got ' + data.status)
    }
    // validate the optional field `payment_account`
    if (data.payment_account) { // data not null
      PaymentAccount.validateJSON(data.payment_account)
    }

    return true
  }
}

/**
 * Pending received document payment total amount
 * @member {Number} amount
 */
PendingReceivedDocumentPaymentsListItem.prototype.amount = undefined

/**
 * Due date
 * @member {Date} due_date
 */
PendingReceivedDocumentPaymentsListItem.prototype.due_date = undefined

/**
 * Pending received document payment paid date
 * @member {Date} paid_date
 */
PendingReceivedDocumentPaymentsListItem.prototype.paid_date = undefined

/**
 * @member {module:model/PendingReceivedDocumentPaymentsListItemPaymentTerms} payment_terms
 */
PendingReceivedDocumentPaymentsListItem.prototype.payment_terms = undefined

/**
 * Pending received document payment status
 * @member {String} status
 */
PendingReceivedDocumentPaymentsListItem.prototype.status = undefined

/**
 * True if paid with TS Pay
 * @member {Boolean} paid_with_ts_pay
 */
PendingReceivedDocumentPaymentsListItem.prototype.paid_with_ts_pay = undefined

/**
 * @member {module:model/PaymentAccount} payment_account
 */
PendingReceivedDocumentPaymentsListItem.prototype.payment_account = undefined

export default PendingReceivedDocumentPaymentsListItem
