/**
 * Fatture in Cloud API v2 - API Reference
 * Connect your software with Fatture in Cloud, the invoicing platform chosen by more than 400.000 businesses in Italy.   The Fatture in Cloud API is based on REST, and makes possible to interact with the user related data prior authorization via OAuth2 protocol. For more information, please visit https://www.fattureincloud.it.
 *
 * The version of the OpenAPI document: 2.0.2
 * Contact: info@fattureincloud.it
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function (root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd() + '/src/index'], factory)
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd() + '/src/index'))
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.fattureInCloudSdk)
  }
}(this, function (expect, fattureInCloudSdk) {
  'use strict'

  let instance

  beforeEach(function () {
    instance = new fattureInCloudSdk.CompanyInfoPlanInfoFunctions()
    instance.document_attachments = true
    instance.archive = true
    instance.payment_notifications = true
    instance.paypal = true
    instance.receipts = true
    instance.e_invoice = true
    instance.genius = true
    instance.stock = true
    instance.smtp = true
    instance.mail_tracking = true
    instance.subaccounts = true
    instance.tessera_sanitaria = true
    instance.recurring = true
    instance.sofort = false
    instance.cerved = true
    instance.ts_digital = true
    instance.ts_pay = true
    instance.ts_invoice_trading = true
  })

  // const getProperty = function (object, getter, property) {
  //   // Use getter method if present; otherwise, get the property directly.
  //   if (typeof object[getter] === 'function') { return object[getter]() } else { return object[property] }
  // }

  // const setProperty = function (object, setter, property, value) {
  //   // Use setter method if present; otherwise, set the property directly.
  //   if (typeof object[setter] === 'function') { object[setter](value) } else { object[property] = value }
  // }

  describe('CompanyInfoPlanInfoFunctions', function () {
    it('should create an instance of CompanyInfoPlanInfoFunctions', function () {
      expect(instance).to.be.a(fattureInCloudSdk.CompanyInfoPlanInfoFunctions)
    })

    it('should have the property archive (base name: "archive")', function () {
      expect(typeof instance.archive).to.be('boolean')
    })

    it('should have the property cerved (base name: "cerved")', function () {
      expect(typeof instance.cerved).to.be('boolean')
    })

    it('should have the property documentAttachments (base name: "document_attachments")', function () {
      expect(typeof instance.document_attachments).to.be('boolean')
    })

    it('should have the property eInvoice (base name: "e_invoice")', function () {
      expect(typeof instance.e_invoice).to.be('boolean')
    })

    it('should have the property genius (base name: "genius")', function () {
      expect(typeof instance.genius).to.be('boolean')
    })

    it('should have the property mailTracking (base name: "mail_tracking")', function () {
      expect(typeof instance.mail_tracking).to.be('boolean')
    })

    it('should have the property paymentNotifications (base name: "payment_notifications")', function () {
      expect(typeof instance.payment_notifications).to.be('boolean')
    })

    it('should have the property paypal (base name: "paypal")', function () {
      expect(typeof instance.paypal).to.be('boolean')
    })

    it('should have the property receipts (base name: "receipts")', function () {
      expect(typeof instance.receipts).to.be('boolean')
    })

    it('should have the property recurring (base name: "recurring")', function () {
      expect(typeof instance.recurring).to.be('boolean')
    })

    it('should have the property smtp (base name: "smtp")', function () {
      expect(typeof instance.smtp).to.be('boolean')
    })

    it('should have the property sofort (base name: "sofort")', function () {
      expect(typeof instance.sofort).to.be('boolean')
    })

    it('should have the property stock (base name: "stock")', function () {
      expect(typeof instance.stock).to.be('boolean')
    })

    it('should have the property subaccounts (base name: "subaccounts")', function () {
      expect(typeof instance.subaccounts).to.be('boolean')
    })

    it('should have the property tesseraSanitaria (base name: "tessera_sanitaria")', function () {
      expect(typeof instance.tessera_sanitaria).to.be('boolean')
    })

    it('should have the property tsDigital (base name: "ts_digital")', function () {
      expect(typeof instance.ts_digital).to.be('boolean')
    })

    it('should have the property tsInvoiceTrading (base name: "ts_invoice_trading")', function () {
      expect(typeof instance.ts_invoice_trading).to.be('boolean')
    })

    it('should have the property tsPay (base name: "ts_pay")', function () {
      expect(typeof instance.ts_pay).to.be('boolean')
    })
  })
}))
