/**
 * Fatture in Cloud API v2 - API Reference
 * Connect your software with Fatture in Cloud, the invoicing platform chosen by more than 400.000 businesses in Italy.   The Fatture in Cloud API is based on REST, and makes possible to interact with the user related data prior authorization via OAuth2 protocol.  For more information, please visit https://www.fattureincloud.it.
 *
 * The version of the OpenAPI document: 2.0.1
 * Contact: info@fattureincloud.it
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.@FattureincloudFattureincloudJsSdk);
  }
}(this, function(expect, @FattureincloudFattureincloudJsSdk) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new @FattureincloudFattureincloudJsSdk.IssuedDocument();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('IssuedDocument', function() {
    it('should create an instance of IssuedDocument', function() {
      // uncomment below and update the code to test IssuedDocument
      //var instane = new @FattureincloudFattureincloudJsSdk.IssuedDocument();
      //expect(instance).to.be.a(@FattureincloudFattureincloudJsSdk.IssuedDocument);
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instance = new @FattureincloudFattureincloudJsSdk.IssuedDocument();
      //expect(instance).to.be();
    });

    it('should have the property entity (base name: "entity")', function() {
      // uncomment below and update the code to test the property entity
      //var instance = new @FattureincloudFattureincloudJsSdk.IssuedDocument();
      //expect(instance).to.be();
    });

    it('should have the property type (base name: "type")', function() {
      // uncomment below and update the code to test the property type
      //var instance = new @FattureincloudFattureincloudJsSdk.IssuedDocument();
      //expect(instance).to.be();
    });

    it('should have the property number (base name: "number")', function() {
      // uncomment below and update the code to test the property number
      //var instance = new @FattureincloudFattureincloudJsSdk.IssuedDocument();
      //expect(instance).to.be();
    });

    it('should have the property numeration (base name: "numeration")', function() {
      // uncomment below and update the code to test the property numeration
      //var instance = new @FattureincloudFattureincloudJsSdk.IssuedDocument();
      //expect(instance).to.be();
    });

    it('should have the property date (base name: "date")', function() {
      // uncomment below and update the code to test the property date
      //var instance = new @FattureincloudFattureincloudJsSdk.IssuedDocument();
      //expect(instance).to.be();
    });

    it('should have the property currency (base name: "currency")', function() {
      // uncomment below and update the code to test the property currency
      //var instance = new @FattureincloudFattureincloudJsSdk.IssuedDocument();
      //expect(instance).to.be();
    });

    it('should have the property language (base name: "language")', function() {
      // uncomment below and update the code to test the property language
      //var instance = new @FattureincloudFattureincloudJsSdk.IssuedDocument();
      //expect(instance).to.be();
    });

    it('should have the property subject (base name: "subject")', function() {
      // uncomment below and update the code to test the property subject
      //var instance = new @FattureincloudFattureincloudJsSdk.IssuedDocument();
      //expect(instance).to.be();
    });

    it('should have the property visibleSubject (base name: "visible_subject")', function() {
      // uncomment below and update the code to test the property visibleSubject
      //var instance = new @FattureincloudFattureincloudJsSdk.IssuedDocument();
      //expect(instance).to.be();
    });

    it('should have the property rcCenter (base name: "rc_center")', function() {
      // uncomment below and update the code to test the property rcCenter
      //var instance = new @FattureincloudFattureincloudJsSdk.IssuedDocument();
      //expect(instance).to.be();
    });

    it('should have the property notes (base name: "notes")', function() {
      // uncomment below and update the code to test the property notes
      //var instance = new @FattureincloudFattureincloudJsSdk.IssuedDocument();
      //expect(instance).to.be();
    });

    it('should have the property rivalsa (base name: "rivalsa")', function() {
      // uncomment below and update the code to test the property rivalsa
      //var instance = new @FattureincloudFattureincloudJsSdk.IssuedDocument();
      //expect(instance).to.be();
    });

    it('should have the property cassa (base name: "cassa")', function() {
      // uncomment below and update the code to test the property cassa
      //var instance = new @FattureincloudFattureincloudJsSdk.IssuedDocument();
      //expect(instance).to.be();
    });

    it('should have the property withholdingTax (base name: "withholding_tax")', function() {
      // uncomment below and update the code to test the property withholdingTax
      //var instance = new @FattureincloudFattureincloudJsSdk.IssuedDocument();
      //expect(instance).to.be();
    });

    it('should have the property withholdingTaxTaxable (base name: "withholding_tax_taxable")', function() {
      // uncomment below and update the code to test the property withholdingTaxTaxable
      //var instance = new @FattureincloudFattureincloudJsSdk.IssuedDocument();
      //expect(instance).to.be();
    });

    it('should have the property otherWithholdingTax (base name: "other_withholding_tax")', function() {
      // uncomment below and update the code to test the property otherWithholdingTax
      //var instance = new @FattureincloudFattureincloudJsSdk.IssuedDocument();
      //expect(instance).to.be();
    });

    it('should have the property stampDuty (base name: "stamp_duty")', function() {
      // uncomment below and update the code to test the property stampDuty
      //var instance = new @FattureincloudFattureincloudJsSdk.IssuedDocument();
      //expect(instance).to.be();
    });

    it('should have the property paymentMethod (base name: "payment_method")', function() {
      // uncomment below and update the code to test the property paymentMethod
      //var instance = new @FattureincloudFattureincloudJsSdk.IssuedDocument();
      //expect(instance).to.be();
    });

    it('should have the property useSplitPayment (base name: "use_split_payment")', function() {
      // uncomment below and update the code to test the property useSplitPayment
      //var instance = new @FattureincloudFattureincloudJsSdk.IssuedDocument();
      //expect(instance).to.be();
    });

    it('should have the property useGrossPrices (base name: "use_gross_prices")', function() {
      // uncomment below and update the code to test the property useGrossPrices
      //var instance = new @FattureincloudFattureincloudJsSdk.IssuedDocument();
      //expect(instance).to.be();
    });

    it('should have the property eInvoice (base name: "e_invoice")', function() {
      // uncomment below and update the code to test the property eInvoice
      //var instance = new @FattureincloudFattureincloudJsSdk.IssuedDocument();
      //expect(instance).to.be();
    });

    it('should have the property eiData (base name: "ei_data")', function() {
      // uncomment below and update the code to test the property eiData
      //var instance = new @FattureincloudFattureincloudJsSdk.IssuedDocument();
      //expect(instance).to.be();
    });

    it('should have the property itemsList (base name: "items_list")', function() {
      // uncomment below and update the code to test the property itemsList
      //var instance = new @FattureincloudFattureincloudJsSdk.IssuedDocument();
      //expect(instance).to.be();
    });

    it('should have the property paymentsList (base name: "payments_list")', function() {
      // uncomment below and update the code to test the property paymentsList
      //var instance = new @FattureincloudFattureincloudJsSdk.IssuedDocument();
      //expect(instance).to.be();
    });

    it('should have the property template (base name: "template")', function() {
      // uncomment below and update the code to test the property template
      //var instance = new @FattureincloudFattureincloudJsSdk.IssuedDocument();
      //expect(instance).to.be();
    });

    it('should have the property deliveryNoteTemplate (base name: "delivery_note_template")', function() {
      // uncomment below and update the code to test the property deliveryNoteTemplate
      //var instance = new @FattureincloudFattureincloudJsSdk.IssuedDocument();
      //expect(instance).to.be();
    });

    it('should have the property accInvTemplate (base name: "acc_inv_template")', function() {
      // uncomment below and update the code to test the property accInvTemplate
      //var instance = new @FattureincloudFattureincloudJsSdk.IssuedDocument();
      //expect(instance).to.be();
    });

    it('should have the property hMargins (base name: "h_margins")', function() {
      // uncomment below and update the code to test the property hMargins
      //var instance = new @FattureincloudFattureincloudJsSdk.IssuedDocument();
      //expect(instance).to.be();
    });

    it('should have the property showPayments (base name: "show_payments")', function() {
      // uncomment below and update the code to test the property showPayments
      //var instance = new @FattureincloudFattureincloudJsSdk.IssuedDocument();
      //expect(instance).to.be();
    });

    it('should have the property showPaymentMethod (base name: "show_payment_method")', function() {
      // uncomment below and update the code to test the property showPaymentMethod
      //var instance = new @FattureincloudFattureincloudJsSdk.IssuedDocument();
      //expect(instance).to.be();
    });

    it('should have the property showTotals (base name: "show_totals")', function() {
      // uncomment below and update the code to test the property showTotals
      //var instance = new @FattureincloudFattureincloudJsSdk.IssuedDocument();
      //expect(instance).to.be();
    });

    it('should have the property vMargins (base name: "v_margins")', function() {
      // uncomment below and update the code to test the property vMargins
      //var instance = new @FattureincloudFattureincloudJsSdk.IssuedDocument();
      //expect(instance).to.be();
    });

    it('should have the property showPaypalButton (base name: "show_paypal_button")', function() {
      // uncomment below and update the code to test the property showPaypalButton
      //var instance = new @FattureincloudFattureincloudJsSdk.IssuedDocument();
      //expect(instance).to.be();
    });

    it('should have the property showNotificationButton (base name: "show_notification_button")', function() {
      // uncomment below and update the code to test the property showNotificationButton
      //var instance = new @FattureincloudFattureincloudJsSdk.IssuedDocument();
      //expect(instance).to.be();
    });

    it('should have the property deliveryNote (base name: "delivery_note")', function() {
      // uncomment below and update the code to test the property deliveryNote
      //var instance = new @FattureincloudFattureincloudJsSdk.IssuedDocument();
      //expect(instance).to.be();
    });

    it('should have the property accompanyingInvoice (base name: "accompanying_invoice")', function() {
      // uncomment below and update the code to test the property accompanyingInvoice
      //var instance = new @FattureincloudFattureincloudJsSdk.IssuedDocument();
      //expect(instance).to.be();
    });

    it('should have the property dnNumber (base name: "dn_number")', function() {
      // uncomment below and update the code to test the property dnNumber
      //var instance = new @FattureincloudFattureincloudJsSdk.IssuedDocument();
      //expect(instance).to.be();
    });

    it('should have the property dnDate (base name: "dn_date")', function() {
      // uncomment below and update the code to test the property dnDate
      //var instance = new @FattureincloudFattureincloudJsSdk.IssuedDocument();
      //expect(instance).to.be();
    });

    it('should have the property dnAiPackagesNumber (base name: "dn_ai_packages_number")', function() {
      // uncomment below and update the code to test the property dnAiPackagesNumber
      //var instance = new @FattureincloudFattureincloudJsSdk.IssuedDocument();
      //expect(instance).to.be();
    });

    it('should have the property dnAiWeight (base name: "dn_ai_weight")', function() {
      // uncomment below and update the code to test the property dnAiWeight
      //var instance = new @FattureincloudFattureincloudJsSdk.IssuedDocument();
      //expect(instance).to.be();
    });

    it('should have the property dnAiCausal (base name: "dn_ai_causal")', function() {
      // uncomment below and update the code to test the property dnAiCausal
      //var instance = new @FattureincloudFattureincloudJsSdk.IssuedDocument();
      //expect(instance).to.be();
    });

    it('should have the property dnAiDestination (base name: "dn_ai_destination")', function() {
      // uncomment below and update the code to test the property dnAiDestination
      //var instance = new @FattureincloudFattureincloudJsSdk.IssuedDocument();
      //expect(instance).to.be();
    });

    it('should have the property dnAiTransporter (base name: "dn_ai_transporter")', function() {
      // uncomment below and update the code to test the property dnAiTransporter
      //var instance = new @FattureincloudFattureincloudJsSdk.IssuedDocument();
      //expect(instance).to.be();
    });

    it('should have the property dnAiNotes (base name: "dn_ai_notes")', function() {
      // uncomment below and update the code to test the property dnAiNotes
      //var instance = new @FattureincloudFattureincloudJsSdk.IssuedDocument();
      //expect(instance).to.be();
    });

    it('should have the property refersTo (base name: "refers_to")', function() {
      // uncomment below and update the code to test the property refersTo
      //var instance = new @FattureincloudFattureincloudJsSdk.IssuedDocument();
      //expect(instance).to.be();
    });

    it('should have the property isMarked (base name: "is_marked")', function() {
      // uncomment below and update the code to test the property isMarked
      //var instance = new @FattureincloudFattureincloudJsSdk.IssuedDocument();
      //expect(instance).to.be();
    });

    it('should have the property amountNet (base name: "amount_net")', function() {
      // uncomment below and update the code to test the property amountNet
      //var instance = new @FattureincloudFattureincloudJsSdk.IssuedDocument();
      //expect(instance).to.be();
    });

    it('should have the property amountVat (base name: "amount_vat")', function() {
      // uncomment below and update the code to test the property amountVat
      //var instance = new @FattureincloudFattureincloudJsSdk.IssuedDocument();
      //expect(instance).to.be();
    });

    it('should have the property amountGross (base name: "amount_gross")', function() {
      // uncomment below and update the code to test the property amountGross
      //var instance = new @FattureincloudFattureincloudJsSdk.IssuedDocument();
      //expect(instance).to.be();
    });

    it('should have the property amountRivalsa (base name: "amount_rivalsa")', function() {
      // uncomment below and update the code to test the property amountRivalsa
      //var instance = new @FattureincloudFattureincloudJsSdk.IssuedDocument();
      //expect(instance).to.be();
    });

    it('should have the property amountCassa (base name: "amount_cassa")', function() {
      // uncomment below and update the code to test the property amountCassa
      //var instance = new @FattureincloudFattureincloudJsSdk.IssuedDocument();
      //expect(instance).to.be();
    });

    it('should have the property amountWithholdingTax (base name: "amount_withholding_tax")', function() {
      // uncomment below and update the code to test the property amountWithholdingTax
      //var instance = new @FattureincloudFattureincloudJsSdk.IssuedDocument();
      //expect(instance).to.be();
    });

    it('should have the property amountOtherWithholdingTax (base name: "amount_other_withholding_tax")', function() {
      // uncomment below and update the code to test the property amountOtherWithholdingTax
      //var instance = new @FattureincloudFattureincloudJsSdk.IssuedDocument();
      //expect(instance).to.be();
    });

    it('should have the property extraData (base name: "extra_data")', function() {
      // uncomment below and update the code to test the property extraData
      //var instance = new @FattureincloudFattureincloudJsSdk.IssuedDocument();
      //expect(instance).to.be();
    });

    it('should have the property seenDate (base name: "seen_date")', function() {
      // uncomment below and update the code to test the property seenDate
      //var instance = new @FattureincloudFattureincloudJsSdk.IssuedDocument();
      //expect(instance).to.be();
    });

    it('should have the property nextDueDate (base name: "next_due_date")', function() {
      // uncomment below and update the code to test the property nextDueDate
      //var instance = new @FattureincloudFattureincloudJsSdk.IssuedDocument();
      //expect(instance).to.be();
    });

    it('should have the property url (base name: "url")', function() {
      // uncomment below and update the code to test the property url
      //var instance = new @FattureincloudFattureincloudJsSdk.IssuedDocument();
      //expect(instance).to.be();
    });

    it('should have the property attachmentUrl (base name: "attachment_url")', function() {
      // uncomment below and update the code to test the property attachmentUrl
      //var instance = new @FattureincloudFattureincloudJsSdk.IssuedDocument();
      //expect(instance).to.be();
    });

    it('should have the property attachmentToken (base name: "attachment_token")', function() {
      // uncomment below and update the code to test the property attachmentToken
      //var instance = new @FattureincloudFattureincloudJsSdk.IssuedDocument();
      //expect(instance).to.be();
    });

    it('should have the property eiRaw (base name: "ei_raw")', function() {
      // uncomment below and update the code to test the property eiRaw
      //var instance = new @FattureincloudFattureincloudJsSdk.IssuedDocument();
      //expect(instance).to.be();
    });

    it('should have the property showTspayButton (base name: "show_tspay_button")', function() {
      // uncomment below and update the code to test the property showTspayButton
      //var instance = new @FattureincloudFattureincloudJsSdk.IssuedDocument();
      //expect(instance).to.be();
    });

    it('should have the property year (base name: "year")', function() {
      // uncomment below and update the code to test the property year
      //var instance = new @FattureincloudFattureincloudJsSdk.IssuedDocument();
      //expect(instance).to.be();
    });

    it('should have the property amountRivalsaTaxable (base name: "amount_rivalsa_taxable")', function() {
      // uncomment below and update the code to test the property amountRivalsaTaxable
      //var instance = new @FattureincloudFattureincloudJsSdk.IssuedDocument();
      //expect(instance).to.be();
    });

    it('should have the property amountGlobalCassaTaxable (base name: "amount_global_cassa_taxable")', function() {
      // uncomment below and update the code to test the property amountGlobalCassaTaxable
      //var instance = new @FattureincloudFattureincloudJsSdk.IssuedDocument();
      //expect(instance).to.be();
    });

    it('should have the property amountCassaTaxable (base name: "amount_cassa_taxable")', function() {
      // uncomment below and update the code to test the property amountCassaTaxable
      //var instance = new @FattureincloudFattureincloudJsSdk.IssuedDocument();
      //expect(instance).to.be();
    });

    it('should have the property amountCassa2 (base name: "amount_cassa2")', function() {
      // uncomment below and update the code to test the property amountCassa2
      //var instance = new @FattureincloudFattureincloudJsSdk.IssuedDocument();
      //expect(instance).to.be();
    });

    it('should have the property amountCassa2Taxable (base name: "amount_cassa2_taxable")', function() {
      // uncomment below and update the code to test the property amountCassa2Taxable
      //var instance = new @FattureincloudFattureincloudJsSdk.IssuedDocument();
      //expect(instance).to.be();
    });

    it('should have the property amountWithholdingTaxTaxable (base name: "amount_withholding_tax_taxable")', function() {
      // uncomment below and update the code to test the property amountWithholdingTaxTaxable
      //var instance = new @FattureincloudFattureincloudJsSdk.IssuedDocument();
      //expect(instance).to.be();
    });

    it('should have the property amountEnasarcoTaxable (base name: "amount_enasarco_taxable")', function() {
      // uncomment below and update the code to test the property amountEnasarcoTaxable
      //var instance = new @FattureincloudFattureincloudJsSdk.IssuedDocument();
      //expect(instance).to.be();
    });

    it('should have the property amountOtherWithholdingTaxTaxable (base name: "amount_other_withholding_tax_taxable")', function() {
      // uncomment below and update the code to test the property amountOtherWithholdingTaxTaxable
      //var instance = new @FattureincloudFattureincloudJsSdk.IssuedDocument();
      //expect(instance).to.be();
    });

    it('should have the property eiCassaType (base name: "ei_cassa_type")', function() {
      // uncomment below and update the code to test the property eiCassaType
      //var instance = new @FattureincloudFattureincloudJsSdk.IssuedDocument();
      //expect(instance).to.be();
    });

    it('should have the property eiCassa2Type (base name: "ei_cassa2_type")', function() {
      // uncomment below and update the code to test the property eiCassa2Type
      //var instance = new @FattureincloudFattureincloudJsSdk.IssuedDocument();
      //expect(instance).to.be();
    });

    it('should have the property eiWithholdingTaxCausal (base name: "ei_withholding_tax_causal")', function() {
      // uncomment below and update the code to test the property eiWithholdingTaxCausal
      //var instance = new @FattureincloudFattureincloudJsSdk.IssuedDocument();
      //expect(instance).to.be();
    });

    it('should have the property eiOtherWithholdingTaxType (base name: "ei_other_withholding_tax_type")', function() {
      // uncomment below and update the code to test the property eiOtherWithholdingTaxType
      //var instance = new @FattureincloudFattureincloudJsSdk.IssuedDocument();
      //expect(instance).to.be();
    });

    it('should have the property eiOtherWithholdingTaxCausal (base name: "ei_other_withholding_tax_causal")', function() {
      // uncomment below and update the code to test the property eiOtherWithholdingTaxCausal
      //var instance = new @FattureincloudFattureincloudJsSdk.IssuedDocument();
      //expect(instance).to.be();
    });

    it('should have the property amountDueDiscount (base name: "amount_due_discount")', function() {
      // uncomment below and update the code to test the property amountDueDiscount
      //var instance = new @FattureincloudFattureincloudJsSdk.IssuedDocument();
      //expect(instance).to.be();
    });

  });

}));
