/**
 * Fatture in Cloud API v2 - API Reference
 * Connect your software with Fatture in Cloud, the invoicing platform chosen by more than 500.000 businesses in Italy.   The Fatture in Cloud API is based on REST, and makes possible to interact with the user related data prior authorization via OAuth2 protocol.
 *
 * The version of the OpenAPI document: 2.1.8
 * Contact: info@fattureincloud.it
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function (root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd() + '/src/index'], factory)
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd() + '/src/index'))
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.fattureInCloudSdk)
  }
}(this, function (expect, fattureInCloudSdk) {
  'use strict'

  let instance

  beforeEach(function () {
    instance = new fattureInCloudSdk.PendingReceivedDocument()
  })

  const getProperty = function (object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function') { return object[getter]() } else { return object[property] }
  }

  const setProperty = function (object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function') { object[setter](value) } else { object[property] = value }
  }

  describe('PendingReceivedDocument', function () {
    it('should create an instance of PendingReceivedDocument', function () {
      // uncomment below and update the code to test PendingReceivedDocument
      // var instance = new fattureInCloudSdk.PendingReceivedDocument();
      // expect(instance).to.be.a(fattureInCloudSdk.PendingReceivedDocument);
    })

    it('should have the property id (base name: "id")', function () {
      // uncomment below and update the code to test the property id
      // var instance = new fattureInCloudSdk.PendingReceivedDocument();
      // expect(instance).to.be();
    })

    it('should have the property date (base name: "date")', function () {
      // uncomment below and update the code to test the property date
      // var instance = new fattureInCloudSdk.PendingReceivedDocument();
      // expect(instance).to.be();
    })

    it('should have the property subject (base name: "subject")', function () {
      // uncomment below and update the code to test the property subject
      // var instance = new fattureInCloudSdk.PendingReceivedDocument();
      // expect(instance).to.be();
    })

    it('should have the property filename (base name: "filename")', function () {
      // uncomment below and update the code to test the property filename
      // var instance = new fattureInCloudSdk.PendingReceivedDocument();
      // expect(instance).to.be();
    })

    it('should have the property type (base name: "type")', function () {
      // uncomment below and update the code to test the property type
      // var instance = new fattureInCloudSdk.PendingReceivedDocument();
      // expect(instance).to.be();
    })

    it('should have the property attachmentUrl (base name: "attachment_url")', function () {
      // uncomment below and update the code to test the property attachmentUrl
      // var instance = new fattureInCloudSdk.PendingReceivedDocument();
      // expect(instance).to.be();
    })

    it('should have the property amountGross (base name: "amount_gross")', function () {
      // uncomment below and update the code to test the property amountGross
      // var instance = new fattureInCloudSdk.PendingReceivedDocument();
      // expect(instance).to.be();
    })

    it('should have the property currency (base name: "currency")', function () {
      // uncomment below and update the code to test the property currency
      // var instance = new fattureInCloudSdk.PendingReceivedDocument();
      // expect(instance).to.be();
    })

    it('should have the property documentType (base name: "document_type")', function () {
      // uncomment below and update the code to test the property documentType
      // var instance = new fattureInCloudSdk.PendingReceivedDocument();
      // expect(instance).to.be();
    })

    it('should have the property supplierName (base name: "supplier_name")', function () {
      // uncomment below and update the code to test the property supplierName
      // var instance = new fattureInCloudSdk.PendingReceivedDocument();
      // expect(instance).to.be();
    })

    it('should have the property costCenter (base name: "cost_center")', function () {
      // uncomment below and update the code to test the property costCenter
      // var instance = new fattureInCloudSdk.PendingReceivedDocument();
      // expect(instance).to.be();
    })

    it('should have the property category (base name: "category")', function () {
      // uncomment below and update the code to test the property category
      // var instance = new fattureInCloudSdk.PendingReceivedDocument();
      // expect(instance).to.be();
    })

    it('should have the property otherAttachments (base name: "other_attachments")', function () {
      // uncomment below and update the code to test the property otherAttachments
      // var instance = new fattureInCloudSdk.PendingReceivedDocument();
      // expect(instance).to.be();
    })

    it('should have the property emssionDate (base name: "emssion_date")', function () {
      // uncomment below and update the code to test the property emssionDate
      // var instance = new fattureInCloudSdk.PendingReceivedDocument();
      // expect(instance).to.be();
    })

    it('should have the property paymentsList (base name: "payments_list")', function () {
      // uncomment below and update the code to test the property paymentsList
      // var instance = new fattureInCloudSdk.PendingReceivedDocument();
      // expect(instance).to.be();
    })

    it('should have the property amountNet (base name: "amount_net")', function () {
      // uncomment below and update the code to test the property amountNet
      // var instance = new fattureInCloudSdk.PendingReceivedDocument();
      // expect(instance).to.be();
    })

    it('should have the property amountVat (base name: "amount_vat")', function () {
      // uncomment below and update the code to test the property amountVat
      // var instance = new fattureInCloudSdk.PendingReceivedDocument();
      // expect(instance).to.be();
    })

    it('should have the property importError (base name: "import_error")', function () {
      // uncomment below and update the code to test the property importError
      // var instance = new fattureInCloudSdk.PendingReceivedDocument();
      // expect(instance).to.be();
    })

    it('should have the property extractedData (base name: "extracted_data")', function () {
      // uncomment below and update the code to test the property extractedData
      // var instance = new fattureInCloudSdk.PendingReceivedDocument();
      // expect(instance).to.be();
    })
  })
}))
