/**
 * Fatture in Cloud API v2 - API Reference
 * Connect your software with Fatture in Cloud, the invoicing platform chosen by more than 400.000 businesses in Italy.   The Fatture in Cloud API is based on REST, and makes possible to interact with the user related data prior authorization via OAuth2 protocol.  For more information, please visit https://www.fattureincloud.it.
 *
 * The version of the OpenAPI document: 2.0.1
 * Contact: info@fattureincloud.it
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/FattureInCloud/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/FattureInCloud/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.fattureInCloudSdk);
  }
}(this, function(expect, fattureInCloudSdk) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new fattureInCloudSdk.ReceiptItemsListItem();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ReceiptItemsListItem', function() {
    it('should create an instance of ReceiptItemsListItem', function() {
      // uncomment below and update the code to test ReceiptItemsListItem
      //var instane = new fattureInCloudSdk.ReceiptItemsListItem();
      //expect(instance).to.be.a(fattureInCloudSdk.ReceiptItemsListItem);
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instance = new fattureInCloudSdk.ReceiptItemsListItem();
      //expect(instance).to.be();
    });

    it('should have the property amountNet (base name: "amount_net")', function() {
      // uncomment below and update the code to test the property amountNet
      //var instance = new fattureInCloudSdk.ReceiptItemsListItem();
      //expect(instance).to.be();
    });

    it('should have the property amountGross (base name: "amount_gross")', function() {
      // uncomment below and update the code to test the property amountGross
      //var instance = new fattureInCloudSdk.ReceiptItemsListItem();
      //expect(instance).to.be();
    });

    it('should have the property category (base name: "category")', function() {
      // uncomment below and update the code to test the property category
      //var instance = new fattureInCloudSdk.ReceiptItemsListItem();
      //expect(instance).to.be();
    });

    it('should have the property vat (base name: "vat")', function() {
      // uncomment below and update the code to test the property vat
      //var instance = new fattureInCloudSdk.ReceiptItemsListItem();
      //expect(instance).to.be();
    });

  });

}));
