/**
 * Fatture in Cloud API v2 - API Reference
 * Connect your software with Fatture in Cloud, the invoicing platform chosen by more than 400.000 businesses in Italy.   The Fatture in Cloud API is based on REST, and makes possible to interact with the user related data prior authorization via OAuth2 protocol.  For more information, please visit https://www.fattureincloud.it.
 *
 * The version of the OpenAPI document: 2.0.1
 * Contact: info@fattureincloud.it
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import ArchiveDocument from './model/ArchiveDocument';
import CashbookEntry from './model/CashbookEntry';
import CashbookEntryData from './model/CashbookEntryData';
import CashbookEntryDataDocument from './model/CashbookEntryDataDocument';
import CashbookEntryIn from './model/CashbookEntryIn';
import CashbookEntryInData from './model/CashbookEntryInData';
import CashbookEntryInOut from './model/CashbookEntryInOut';
import CashbookEntryOut from './model/CashbookEntryOut';
import CashbookEntryOutData from './model/CashbookEntryOutData';
import City from './model/City';
import Client from './model/Client';
import Company from './model/Company';
import CompanyInfo from './model/CompanyInfo';
import CompanyInfoAccessInfo from './model/CompanyInfoAccessInfo';
import CompanyInfoPlanInfo from './model/CompanyInfoPlanInfo';
import CompanyInfoPlanInfoFunctions from './model/CompanyInfoPlanInfoFunctions';
import CompanyInfoPlanInfoFunctionsStatus from './model/CompanyInfoPlanInfoFunctionsStatus';
import CompanyInfoPlanInfoLimits from './model/CompanyInfoPlanInfoLimits';
import CreateArchiveDocumentRequest from './model/CreateArchiveDocumentRequest';
import CreateArchiveDocumentResponse from './model/CreateArchiveDocumentResponse';
import CreateCashbookEntryRequest from './model/CreateCashbookEntryRequest';
import CreateCashbookEntryResponse from './model/CreateCashbookEntryResponse';
import CreateClientRequest from './model/CreateClientRequest';
import CreateClientResponse from './model/CreateClientResponse';
import CreateF24Request from './model/CreateF24Request';
import CreateF24Response from './model/CreateF24Response';
import CreateIssuedDocumentRequest from './model/CreateIssuedDocumentRequest';
import CreateIssuedDocumentResponse from './model/CreateIssuedDocumentResponse';
import CreatePaymentAccountRequest from './model/CreatePaymentAccountRequest';
import CreatePaymentAccountResponse from './model/CreatePaymentAccountResponse';
import CreatePaymentMethodRequest from './model/CreatePaymentMethodRequest';
import CreatePaymentMethodResponse from './model/CreatePaymentMethodResponse';
import CreateProductRequest from './model/CreateProductRequest';
import CreateProductResponse from './model/CreateProductResponse';
import CreateReceiptRequest from './model/CreateReceiptRequest';
import CreateReceiptResponse from './model/CreateReceiptResponse';
import CreateReceivedDocumentRequest from './model/CreateReceivedDocumentRequest';
import CreateReceivedDocumentResponse from './model/CreateReceivedDocumentResponse';
import CreateSupplierRequest from './model/CreateSupplierRequest';
import CreateSupplierResponse from './model/CreateSupplierResponse';
import Currency from './model/Currency';
import DocumentTemplate from './model/DocumentTemplate';
import EmailData from './model/EmailData';
import EmailDataDefaultSenderEmail from './model/EmailDataDefaultSenderEmail';
import EmailDataSenderEmailsList from './model/EmailDataSenderEmailsList';
import EmailSchedule from './model/EmailSchedule';
import EmailScheduleInclude from './model/EmailScheduleInclude';
import Entity from './model/Entity';
import EntityOptions from './model/EntityOptions';
import F24 from './model/F24';
import FunctionStatus from './model/FunctionStatus';
import GetArchiveDocumentResponse from './model/GetArchiveDocumentResponse';
import GetCashbookEntryResponse from './model/GetCashbookEntryResponse';
import GetClientResponse from './model/GetClientResponse';
import GetCompanyInfoResponse from './model/GetCompanyInfoResponse';
import GetEmailDataResponse from './model/GetEmailDataResponse';
import GetExistingIssuedDocumentTotalsRequest from './model/GetExistingIssuedDocumentTotalsRequest';
import GetExistingIssuedDocumentTotalsResponse from './model/GetExistingIssuedDocumentTotalsResponse';
import GetExistingReceivedDocumentTotalsRequest from './model/GetExistingReceivedDocumentTotalsRequest';
import GetExistingReceivedDocumentTotalsResponse from './model/GetExistingReceivedDocumentTotalsResponse';
import GetF24Response from './model/GetF24Response';
import GetIssuedDocumentPreCreateInfoResponse from './model/GetIssuedDocumentPreCreateInfoResponse';
import GetIssuedDocumentResponse from './model/GetIssuedDocumentResponse';
import GetNewIssuedDocumentTotalsRequest from './model/GetNewIssuedDocumentTotalsRequest';
import GetNewIssuedDocumentTotalsResponse from './model/GetNewIssuedDocumentTotalsResponse';
import GetNewReceivedDocumentTotalsRequest from './model/GetNewReceivedDocumentTotalsRequest';
import GetNewReceivedDocumentTotalsResponse from './model/GetNewReceivedDocumentTotalsResponse';
import GetPaymentAccountResponse from './model/GetPaymentAccountResponse';
import GetPaymentMethodResponse from './model/GetPaymentMethodResponse';
import GetProductResponse from './model/GetProductResponse';
import GetReceiptPreCreateInfoResponse from './model/GetReceiptPreCreateInfoResponse';
import GetReceiptResponse from './model/GetReceiptResponse';
import GetReceiptsMonthlyTotalsResponse from './model/GetReceiptsMonthlyTotalsResponse';
import GetReceivedDocumentPreCreateInfoResponse from './model/GetReceivedDocumentPreCreateInfoResponse';
import GetReceivedDocumentResponse from './model/GetReceivedDocumentResponse';
import GetSupplierResponse from './model/GetSupplierResponse';
import GetUserInfoResponse from './model/GetUserInfoResponse';
import GetUserInfoResponseEmailConfirmationState from './model/GetUserInfoResponseEmailConfirmationState';
import GetUserInfoResponseInfo from './model/GetUserInfoResponseInfo';
import IssuedDocument from './model/IssuedDocument';
import IssuedDocumentEiData from './model/IssuedDocumentEiData';
import IssuedDocumentExtraData from './model/IssuedDocumentExtraData';
import IssuedDocumentItemsList from './model/IssuedDocumentItemsList';
import IssuedDocumentPaymentsList from './model/IssuedDocumentPaymentsList';
import IssuedDocumentPreCreateInfo from './model/IssuedDocumentPreCreateInfo';
import IssuedDocumentPreCreateInfoDefaultValues from './model/IssuedDocumentPreCreateInfoDefaultValues';
import IssuedDocumentPreCreateInfoExtraDataDefaultValues from './model/IssuedDocumentPreCreateInfoExtraDataDefaultValues';
import IssuedDocumentPreCreateInfoItemsDefaultValues from './model/IssuedDocumentPreCreateInfoItemsDefaultValues';
import IssuedDocumentRefersTo from './model/IssuedDocumentRefersTo';
import IssuedDocumentTotals from './model/IssuedDocumentTotals';
import IssuedDocumentTotalsVatList from './model/IssuedDocumentTotalsVatList';
import IssuedDocumentTotalsVatListVatItem from './model/IssuedDocumentTotalsVatListVatItem';
import IssuedDocumentType from './model/IssuedDocumentType';
import Language from './model/Language';
import ListArchiveCategoriesResponse from './model/ListArchiveCategoriesResponse';
import ListArchiveDocumentsResponse from './model/ListArchiveDocumentsResponse';
import ListArchiveDocumentsResponsePage from './model/ListArchiveDocumentsResponsePage';
import ListCashbookEntriesResponse from './model/ListCashbookEntriesResponse';
import ListCitiesResponse from './model/ListCitiesResponse';
import ListClientsResponse from './model/ListClientsResponse';
import ListClientsResponsePage from './model/ListClientsResponsePage';
import ListCostCentersResponse from './model/ListCostCentersResponse';
import ListCountriesResponse from './model/ListCountriesResponse';
import ListCurrenciesResponse from './model/ListCurrenciesResponse';
import ListDeliveryNotesDefaultCausalsResponse from './model/ListDeliveryNotesDefaultCausalsResponse';
import ListF24Response from './model/ListF24Response';
import ListF24ResponseAggregatedData from './model/ListF24ResponseAggregatedData';
import ListF24ResponseAggregatedDataAggregatedData from './model/ListF24ResponseAggregatedDataAggregatedData';
import ListF24ResponsePage from './model/ListF24ResponsePage';
import ListIssuedDocumentsResponse from './model/ListIssuedDocumentsResponse';
import ListIssuedDocumentsResponsePage from './model/ListIssuedDocumentsResponsePage';
import ListLanguagesResponse from './model/ListLanguagesResponse';
import ListPaymentAccountsResponse from './model/ListPaymentAccountsResponse';
import ListPaymentMethodsResponse from './model/ListPaymentMethodsResponse';
import ListProductCategoriesResponse from './model/ListProductCategoriesResponse';
import ListProductsResponse from './model/ListProductsResponse';
import ListProductsResponsePage from './model/ListProductsResponsePage';
import ListReceiptsResponse from './model/ListReceiptsResponse';
import ListReceiptsResponsePage from './model/ListReceiptsResponsePage';
import ListReceivedDocumentCategoriesResponse from './model/ListReceivedDocumentCategoriesResponse';
import ListReceivedDocumentsResponse from './model/ListReceivedDocumentsResponse';
import ListReceivedDocumentsResponsePage from './model/ListReceivedDocumentsResponsePage';
import ListRevenueCentersResponse from './model/ListRevenueCentersResponse';
import ListSuppliersResponse from './model/ListSuppliersResponse';
import ListSuppliersResponsePage from './model/ListSuppliersResponsePage';
import ListTemplatesResponse from './model/ListTemplatesResponse';
import ListUnitsOfMeasureResponse from './model/ListUnitsOfMeasureResponse';
import ListUserCompaniesResponse from './model/ListUserCompaniesResponse';
import ListUserCompaniesResponseData from './model/ListUserCompaniesResponseData';
import ListVatTypesResponse from './model/ListVatTypesResponse';
import ModifyArchiveDocumentRequest from './model/ModifyArchiveDocumentRequest';
import ModifyArchiveDocumentResponse from './model/ModifyArchiveDocumentResponse';
import ModifyCashbookEntryRequest from './model/ModifyCashbookEntryRequest';
import ModifyCashbookEntryResponse from './model/ModifyCashbookEntryResponse';
import ModifyClientRequest from './model/ModifyClientRequest';
import ModifyClientResponse from './model/ModifyClientResponse';
import ModifyF24Request from './model/ModifyF24Request';
import ModifyF24Response from './model/ModifyF24Response';
import ModifyIssuedDocumentRequest from './model/ModifyIssuedDocumentRequest';
import ModifyIssuedDocumentResponse from './model/ModifyIssuedDocumentResponse';
import ModifyPaymentAccountRequest from './model/ModifyPaymentAccountRequest';
import ModifyPaymentAccountResponse from './model/ModifyPaymentAccountResponse';
import ModifyPaymentMethodRequest from './model/ModifyPaymentMethodRequest';
import ModifyPaymentMethodResponse from './model/ModifyPaymentMethodResponse';
import ModifyProductRequest from './model/ModifyProductRequest';
import ModifyProductResponse from './model/ModifyProductResponse';
import ModifyReceiptRequest from './model/ModifyReceiptRequest';
import ModifyReceiptResponse from './model/ModifyReceiptResponse';
import ModifyReceivedDocumentRequest from './model/ModifyReceivedDocumentRequest';
import ModifyReceivedDocumentResponse from './model/ModifyReceivedDocumentResponse';
import ModifySupplierRequest from './model/ModifySupplierRequest';
import ModifySupplierResponse from './model/ModifySupplierResponse';
import MonthlyTotal from './model/MonthlyTotal';
import Pagination from './model/Pagination';
import PaymentAccount from './model/PaymentAccount';
import PaymentMethod from './model/PaymentMethod';
import PaymentMethodDetails from './model/PaymentMethodDetails';
import PermissionLevel from './model/PermissionLevel';
import Permissions from './model/Permissions';
import PermissionsFicIssuedDocumentsDetailed from './model/PermissionsFicIssuedDocumentsDetailed';
import Product from './model/Product';
import Receipt from './model/Receipt';
import ReceiptItemsListItem from './model/ReceiptItemsListItem';
import ReceiptPreCreateInfo from './model/ReceiptPreCreateInfo';
import ReceiptType from './model/ReceiptType';
import ReceivedDocument from './model/ReceivedDocument';
import ReceivedDocumentEntity from './model/ReceivedDocumentEntity';
import ReceivedDocumentInfo from './model/ReceivedDocumentInfo';
import ReceivedDocumentInfoDefaultValues from './model/ReceivedDocumentInfoDefaultValues';
import ReceivedDocumentInfoItemsDefaultValues from './model/ReceivedDocumentInfoItemsDefaultValues';
import ReceivedDocumentItemsList from './model/ReceivedDocumentItemsList';
import ReceivedDocumentPaymentTerms from './model/ReceivedDocumentPaymentTerms';
import ReceivedDocumentPaymentsList from './model/ReceivedDocumentPaymentsList';
import ReceivedDocumentTotals from './model/ReceivedDocumentTotals';
import ReceivedDocumentType from './model/ReceivedDocumentType';
import ScheduleEmailRequest from './model/ScheduleEmailRequest';
import SendEInvoiceRequest from './model/SendEInvoiceRequest';
import SendEInvoiceRequestData from './model/SendEInvoiceRequestData';
import SendEInvoiceResponse from './model/SendEInvoiceResponse';
import SendEInvoiceResponseData from './model/SendEInvoiceResponseData';
import Supplier from './model/Supplier';
import UploadArchiveAttachmentResponse from './model/UploadArchiveAttachmentResponse';
import UploadF24AttachmentResponse from './model/UploadF24AttachmentResponse';
import UploadIssuedDocumentAttachmentResponse from './model/UploadIssuedDocumentAttachmentResponse';
import UploadIssuedDocumentAttachmentResponseData from './model/UploadIssuedDocumentAttachmentResponseData';
import UploadReceivedDocumentAttachmentResponse from './model/UploadReceivedDocumentAttachmentResponse';
import UploadReceivedDocumentAttachmentResponseData from './model/UploadReceivedDocumentAttachmentResponseData';
import User from './model/User';
import VatType from './model/VatType';
import VerifyEInvoiceXmlErrorResponse from './model/VerifyEInvoiceXmlErrorResponse';
import VerifyEInvoiceXmlErrorResponseError from './model/VerifyEInvoiceXmlErrorResponseError';
import VerifyEInvoiceXmlErrorResponseExtra from './model/VerifyEInvoiceXmlErrorResponseExtra';
import VerifyEInvoiceXmlResponse from './model/VerifyEInvoiceXmlResponse';
import VerifyEInvoiceXmlSuccessResponse from './model/VerifyEInvoiceXmlSuccessResponse';
import VerifyEInvoiceXmlSuccessResponseData from './model/VerifyEInvoiceXmlSuccessResponseData';
import ArchiveApi from './api/ArchiveApi';
import CashbookApi from './api/CashbookApi';
import ClientsApi from './api/ClientsApi';
import CompaniesApi from './api/CompaniesApi';
import InfoApi from './api/InfoApi';
import IssuedDocumentsApi from './api/IssuedDocumentsApi';
import IssuedEInvoicesApi from './api/IssuedEInvoicesApi';
import ProductsApi from './api/ProductsApi';
import ReceiptsApi from './api/ReceiptsApi';
import ReceivedDocumentsApi from './api/ReceivedDocumentsApi';
import SettingsApi from './api/SettingsApi';
import SuppliersApi from './api/SuppliersApi';
import TaxesApi from './api/TaxesApi';
import UserApi from './api/UserApi';


/**
* JavaScript SDK for the Fatture in Cloud API.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var @FattureincloudFattureincloudJsSdk = require('index'); // See note below*.
* var xxxSvc = new @FattureincloudFattureincloudJsSdk.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new @FattureincloudFattureincloudJsSdk.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new @FattureincloudFattureincloudJsSdk.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new @FattureincloudFattureincloudJsSdk.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 2.0.1
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The ArchiveDocument model constructor.
     * @property {module:model/ArchiveDocument}
     */
    ArchiveDocument,

    /**
     * The CashbookEntry model constructor.
     * @property {module:model/CashbookEntry}
     */
    CashbookEntry,

    /**
     * The CashbookEntryData model constructor.
     * @property {module:model/CashbookEntryData}
     */
    CashbookEntryData,

    /**
     * The CashbookEntryDataDocument model constructor.
     * @property {module:model/CashbookEntryDataDocument}
     */
    CashbookEntryDataDocument,

    /**
     * The CashbookEntryIn model constructor.
     * @property {module:model/CashbookEntryIn}
     */
    CashbookEntryIn,

    /**
     * The CashbookEntryInData model constructor.
     * @property {module:model/CashbookEntryInData}
     */
    CashbookEntryInData,

    /**
     * The CashbookEntryInOut model constructor.
     * @property {module:model/CashbookEntryInOut}
     */
    CashbookEntryInOut,

    /**
     * The CashbookEntryOut model constructor.
     * @property {module:model/CashbookEntryOut}
     */
    CashbookEntryOut,

    /**
     * The CashbookEntryOutData model constructor.
     * @property {module:model/CashbookEntryOutData}
     */
    CashbookEntryOutData,

    /**
     * The City model constructor.
     * @property {module:model/City}
     */
    City,

    /**
     * The Client model constructor.
     * @property {module:model/Client}
     */
    Client,

    /**
     * The Company model constructor.
     * @property {module:model/Company}
     */
    Company,

    /**
     * The CompanyInfo model constructor.
     * @property {module:model/CompanyInfo}
     */
    CompanyInfo,

    /**
     * The CompanyInfoAccessInfo model constructor.
     * @property {module:model/CompanyInfoAccessInfo}
     */
    CompanyInfoAccessInfo,

    /**
     * The CompanyInfoPlanInfo model constructor.
     * @property {module:model/CompanyInfoPlanInfo}
     */
    CompanyInfoPlanInfo,

    /**
     * The CompanyInfoPlanInfoFunctions model constructor.
     * @property {module:model/CompanyInfoPlanInfoFunctions}
     */
    CompanyInfoPlanInfoFunctions,

    /**
     * The CompanyInfoPlanInfoFunctionsStatus model constructor.
     * @property {module:model/CompanyInfoPlanInfoFunctionsStatus}
     */
    CompanyInfoPlanInfoFunctionsStatus,

    /**
     * The CompanyInfoPlanInfoLimits model constructor.
     * @property {module:model/CompanyInfoPlanInfoLimits}
     */
    CompanyInfoPlanInfoLimits,

    /**
     * The CreateArchiveDocumentRequest model constructor.
     * @property {module:model/CreateArchiveDocumentRequest}
     */
    CreateArchiveDocumentRequest,

    /**
     * The CreateArchiveDocumentResponse model constructor.
     * @property {module:model/CreateArchiveDocumentResponse}
     */
    CreateArchiveDocumentResponse,

    /**
     * The CreateCashbookEntryRequest model constructor.
     * @property {module:model/CreateCashbookEntryRequest}
     */
    CreateCashbookEntryRequest,

    /**
     * The CreateCashbookEntryResponse model constructor.
     * @property {module:model/CreateCashbookEntryResponse}
     */
    CreateCashbookEntryResponse,

    /**
     * The CreateClientRequest model constructor.
     * @property {module:model/CreateClientRequest}
     */
    CreateClientRequest,

    /**
     * The CreateClientResponse model constructor.
     * @property {module:model/CreateClientResponse}
     */
    CreateClientResponse,

    /**
     * The CreateF24Request model constructor.
     * @property {module:model/CreateF24Request}
     */
    CreateF24Request,

    /**
     * The CreateF24Response model constructor.
     * @property {module:model/CreateF24Response}
     */
    CreateF24Response,

    /**
     * The CreateIssuedDocumentRequest model constructor.
     * @property {module:model/CreateIssuedDocumentRequest}
     */
    CreateIssuedDocumentRequest,

    /**
     * The CreateIssuedDocumentResponse model constructor.
     * @property {module:model/CreateIssuedDocumentResponse}
     */
    CreateIssuedDocumentResponse,

    /**
     * The CreatePaymentAccountRequest model constructor.
     * @property {module:model/CreatePaymentAccountRequest}
     */
    CreatePaymentAccountRequest,

    /**
     * The CreatePaymentAccountResponse model constructor.
     * @property {module:model/CreatePaymentAccountResponse}
     */
    CreatePaymentAccountResponse,

    /**
     * The CreatePaymentMethodRequest model constructor.
     * @property {module:model/CreatePaymentMethodRequest}
     */
    CreatePaymentMethodRequest,

    /**
     * The CreatePaymentMethodResponse model constructor.
     * @property {module:model/CreatePaymentMethodResponse}
     */
    CreatePaymentMethodResponse,

    /**
     * The CreateProductRequest model constructor.
     * @property {module:model/CreateProductRequest}
     */
    CreateProductRequest,

    /**
     * The CreateProductResponse model constructor.
     * @property {module:model/CreateProductResponse}
     */
    CreateProductResponse,

    /**
     * The CreateReceiptRequest model constructor.
     * @property {module:model/CreateReceiptRequest}
     */
    CreateReceiptRequest,

    /**
     * The CreateReceiptResponse model constructor.
     * @property {module:model/CreateReceiptResponse}
     */
    CreateReceiptResponse,

    /**
     * The CreateReceivedDocumentRequest model constructor.
     * @property {module:model/CreateReceivedDocumentRequest}
     */
    CreateReceivedDocumentRequest,

    /**
     * The CreateReceivedDocumentResponse model constructor.
     * @property {module:model/CreateReceivedDocumentResponse}
     */
    CreateReceivedDocumentResponse,

    /**
     * The CreateSupplierRequest model constructor.
     * @property {module:model/CreateSupplierRequest}
     */
    CreateSupplierRequest,

    /**
     * The CreateSupplierResponse model constructor.
     * @property {module:model/CreateSupplierResponse}
     */
    CreateSupplierResponse,

    /**
     * The Currency model constructor.
     * @property {module:model/Currency}
     */
    Currency,

    /**
     * The DocumentTemplate model constructor.
     * @property {module:model/DocumentTemplate}
     */
    DocumentTemplate,

    /**
     * The EmailData model constructor.
     * @property {module:model/EmailData}
     */
    EmailData,

    /**
     * The EmailDataDefaultSenderEmail model constructor.
     * @property {module:model/EmailDataDefaultSenderEmail}
     */
    EmailDataDefaultSenderEmail,

    /**
     * The EmailDataSenderEmailsList model constructor.
     * @property {module:model/EmailDataSenderEmailsList}
     */
    EmailDataSenderEmailsList,

    /**
     * The EmailSchedule model constructor.
     * @property {module:model/EmailSchedule}
     */
    EmailSchedule,

    /**
     * The EmailScheduleInclude model constructor.
     * @property {module:model/EmailScheduleInclude}
     */
    EmailScheduleInclude,

    /**
     * The Entity model constructor.
     * @property {module:model/Entity}
     */
    Entity,

    /**
     * The EntityOptions model constructor.
     * @property {module:model/EntityOptions}
     */
    EntityOptions,

    /**
     * The F24 model constructor.
     * @property {module:model/F24}
     */
    F24,

    /**
     * The FunctionStatus model constructor.
     * @property {module:model/FunctionStatus}
     */
    FunctionStatus,

    /**
     * The GetArchiveDocumentResponse model constructor.
     * @property {module:model/GetArchiveDocumentResponse}
     */
    GetArchiveDocumentResponse,

    /**
     * The GetCashbookEntryResponse model constructor.
     * @property {module:model/GetCashbookEntryResponse}
     */
    GetCashbookEntryResponse,

    /**
     * The GetClientResponse model constructor.
     * @property {module:model/GetClientResponse}
     */
    GetClientResponse,

    /**
     * The GetCompanyInfoResponse model constructor.
     * @property {module:model/GetCompanyInfoResponse}
     */
    GetCompanyInfoResponse,

    /**
     * The GetEmailDataResponse model constructor.
     * @property {module:model/GetEmailDataResponse}
     */
    GetEmailDataResponse,

    /**
     * The GetExistingIssuedDocumentTotalsRequest model constructor.
     * @property {module:model/GetExistingIssuedDocumentTotalsRequest}
     */
    GetExistingIssuedDocumentTotalsRequest,

    /**
     * The GetExistingIssuedDocumentTotalsResponse model constructor.
     * @property {module:model/GetExistingIssuedDocumentTotalsResponse}
     */
    GetExistingIssuedDocumentTotalsResponse,

    /**
     * The GetExistingReceivedDocumentTotalsRequest model constructor.
     * @property {module:model/GetExistingReceivedDocumentTotalsRequest}
     */
    GetExistingReceivedDocumentTotalsRequest,

    /**
     * The GetExistingReceivedDocumentTotalsResponse model constructor.
     * @property {module:model/GetExistingReceivedDocumentTotalsResponse}
     */
    GetExistingReceivedDocumentTotalsResponse,

    /**
     * The GetF24Response model constructor.
     * @property {module:model/GetF24Response}
     */
    GetF24Response,

    /**
     * The GetIssuedDocumentPreCreateInfoResponse model constructor.
     * @property {module:model/GetIssuedDocumentPreCreateInfoResponse}
     */
    GetIssuedDocumentPreCreateInfoResponse,

    /**
     * The GetIssuedDocumentResponse model constructor.
     * @property {module:model/GetIssuedDocumentResponse}
     */
    GetIssuedDocumentResponse,

    /**
     * The GetNewIssuedDocumentTotalsRequest model constructor.
     * @property {module:model/GetNewIssuedDocumentTotalsRequest}
     */
    GetNewIssuedDocumentTotalsRequest,

    /**
     * The GetNewIssuedDocumentTotalsResponse model constructor.
     * @property {module:model/GetNewIssuedDocumentTotalsResponse}
     */
    GetNewIssuedDocumentTotalsResponse,

    /**
     * The GetNewReceivedDocumentTotalsRequest model constructor.
     * @property {module:model/GetNewReceivedDocumentTotalsRequest}
     */
    GetNewReceivedDocumentTotalsRequest,

    /**
     * The GetNewReceivedDocumentTotalsResponse model constructor.
     * @property {module:model/GetNewReceivedDocumentTotalsResponse}
     */
    GetNewReceivedDocumentTotalsResponse,

    /**
     * The GetPaymentAccountResponse model constructor.
     * @property {module:model/GetPaymentAccountResponse}
     */
    GetPaymentAccountResponse,

    /**
     * The GetPaymentMethodResponse model constructor.
     * @property {module:model/GetPaymentMethodResponse}
     */
    GetPaymentMethodResponse,

    /**
     * The GetProductResponse model constructor.
     * @property {module:model/GetProductResponse}
     */
    GetProductResponse,

    /**
     * The GetReceiptPreCreateInfoResponse model constructor.
     * @property {module:model/GetReceiptPreCreateInfoResponse}
     */
    GetReceiptPreCreateInfoResponse,

    /**
     * The GetReceiptResponse model constructor.
     * @property {module:model/GetReceiptResponse}
     */
    GetReceiptResponse,

    /**
     * The GetReceiptsMonthlyTotalsResponse model constructor.
     * @property {module:model/GetReceiptsMonthlyTotalsResponse}
     */
    GetReceiptsMonthlyTotalsResponse,

    /**
     * The GetReceivedDocumentPreCreateInfoResponse model constructor.
     * @property {module:model/GetReceivedDocumentPreCreateInfoResponse}
     */
    GetReceivedDocumentPreCreateInfoResponse,

    /**
     * The GetReceivedDocumentResponse model constructor.
     * @property {module:model/GetReceivedDocumentResponse}
     */
    GetReceivedDocumentResponse,

    /**
     * The GetSupplierResponse model constructor.
     * @property {module:model/GetSupplierResponse}
     */
    GetSupplierResponse,

    /**
     * The GetUserInfoResponse model constructor.
     * @property {module:model/GetUserInfoResponse}
     */
    GetUserInfoResponse,

    /**
     * The GetUserInfoResponseEmailConfirmationState model constructor.
     * @property {module:model/GetUserInfoResponseEmailConfirmationState}
     */
    GetUserInfoResponseEmailConfirmationState,

    /**
     * The GetUserInfoResponseInfo model constructor.
     * @property {module:model/GetUserInfoResponseInfo}
     */
    GetUserInfoResponseInfo,

    /**
     * The IssuedDocument model constructor.
     * @property {module:model/IssuedDocument}
     */
    IssuedDocument,

    /**
     * The IssuedDocumentEiData model constructor.
     * @property {module:model/IssuedDocumentEiData}
     */
    IssuedDocumentEiData,

    /**
     * The IssuedDocumentExtraData model constructor.
     * @property {module:model/IssuedDocumentExtraData}
     */
    IssuedDocumentExtraData,

    /**
     * The IssuedDocumentItemsList model constructor.
     * @property {module:model/IssuedDocumentItemsList}
     */
    IssuedDocumentItemsList,

    /**
     * The IssuedDocumentPaymentsList model constructor.
     * @property {module:model/IssuedDocumentPaymentsList}
     */
    IssuedDocumentPaymentsList,

    /**
     * The IssuedDocumentPreCreateInfo model constructor.
     * @property {module:model/IssuedDocumentPreCreateInfo}
     */
    IssuedDocumentPreCreateInfo,

    /**
     * The IssuedDocumentPreCreateInfoDefaultValues model constructor.
     * @property {module:model/IssuedDocumentPreCreateInfoDefaultValues}
     */
    IssuedDocumentPreCreateInfoDefaultValues,

    /**
     * The IssuedDocumentPreCreateInfoExtraDataDefaultValues model constructor.
     * @property {module:model/IssuedDocumentPreCreateInfoExtraDataDefaultValues}
     */
    IssuedDocumentPreCreateInfoExtraDataDefaultValues,

    /**
     * The IssuedDocumentPreCreateInfoItemsDefaultValues model constructor.
     * @property {module:model/IssuedDocumentPreCreateInfoItemsDefaultValues}
     */
    IssuedDocumentPreCreateInfoItemsDefaultValues,

    /**
     * The IssuedDocumentRefersTo model constructor.
     * @property {module:model/IssuedDocumentRefersTo}
     */
    IssuedDocumentRefersTo,

    /**
     * The IssuedDocumentTotals model constructor.
     * @property {module:model/IssuedDocumentTotals}
     */
    IssuedDocumentTotals,

    /**
     * The IssuedDocumentTotalsVatList model constructor.
     * @property {module:model/IssuedDocumentTotalsVatList}
     */
    IssuedDocumentTotalsVatList,

    /**
     * The IssuedDocumentTotalsVatListVatItem model constructor.
     * @property {module:model/IssuedDocumentTotalsVatListVatItem}
     */
    IssuedDocumentTotalsVatListVatItem,

    /**
     * The IssuedDocumentType model constructor.
     * @property {module:model/IssuedDocumentType}
     */
    IssuedDocumentType,

    /**
     * The Language model constructor.
     * @property {module:model/Language}
     */
    Language,

    /**
     * The ListArchiveCategoriesResponse model constructor.
     * @property {module:model/ListArchiveCategoriesResponse}
     */
    ListArchiveCategoriesResponse,

    /**
     * The ListArchiveDocumentsResponse model constructor.
     * @property {module:model/ListArchiveDocumentsResponse}
     */
    ListArchiveDocumentsResponse,

    /**
     * The ListArchiveDocumentsResponsePage model constructor.
     * @property {module:model/ListArchiveDocumentsResponsePage}
     */
    ListArchiveDocumentsResponsePage,

    /**
     * The ListCashbookEntriesResponse model constructor.
     * @property {module:model/ListCashbookEntriesResponse}
     */
    ListCashbookEntriesResponse,

    /**
     * The ListCitiesResponse model constructor.
     * @property {module:model/ListCitiesResponse}
     */
    ListCitiesResponse,

    /**
     * The ListClientsResponse model constructor.
     * @property {module:model/ListClientsResponse}
     */
    ListClientsResponse,

    /**
     * The ListClientsResponsePage model constructor.
     * @property {module:model/ListClientsResponsePage}
     */
    ListClientsResponsePage,

    /**
     * The ListCostCentersResponse model constructor.
     * @property {module:model/ListCostCentersResponse}
     */
    ListCostCentersResponse,

    /**
     * The ListCountriesResponse model constructor.
     * @property {module:model/ListCountriesResponse}
     */
    ListCountriesResponse,

    /**
     * The ListCurrenciesResponse model constructor.
     * @property {module:model/ListCurrenciesResponse}
     */
    ListCurrenciesResponse,

    /**
     * The ListDeliveryNotesDefaultCausalsResponse model constructor.
     * @property {module:model/ListDeliveryNotesDefaultCausalsResponse}
     */
    ListDeliveryNotesDefaultCausalsResponse,

    /**
     * The ListF24Response model constructor.
     * @property {module:model/ListF24Response}
     */
    ListF24Response,

    /**
     * The ListF24ResponseAggregatedData model constructor.
     * @property {module:model/ListF24ResponseAggregatedData}
     */
    ListF24ResponseAggregatedData,

    /**
     * The ListF24ResponseAggregatedDataAggregatedData model constructor.
     * @property {module:model/ListF24ResponseAggregatedDataAggregatedData}
     */
    ListF24ResponseAggregatedDataAggregatedData,

    /**
     * The ListF24ResponsePage model constructor.
     * @property {module:model/ListF24ResponsePage}
     */
    ListF24ResponsePage,

    /**
     * The ListIssuedDocumentsResponse model constructor.
     * @property {module:model/ListIssuedDocumentsResponse}
     */
    ListIssuedDocumentsResponse,

    /**
     * The ListIssuedDocumentsResponsePage model constructor.
     * @property {module:model/ListIssuedDocumentsResponsePage}
     */
    ListIssuedDocumentsResponsePage,

    /**
     * The ListLanguagesResponse model constructor.
     * @property {module:model/ListLanguagesResponse}
     */
    ListLanguagesResponse,

    /**
     * The ListPaymentAccountsResponse model constructor.
     * @property {module:model/ListPaymentAccountsResponse}
     */
    ListPaymentAccountsResponse,

    /**
     * The ListPaymentMethodsResponse model constructor.
     * @property {module:model/ListPaymentMethodsResponse}
     */
    ListPaymentMethodsResponse,

    /**
     * The ListProductCategoriesResponse model constructor.
     * @property {module:model/ListProductCategoriesResponse}
     */
    ListProductCategoriesResponse,

    /**
     * The ListProductsResponse model constructor.
     * @property {module:model/ListProductsResponse}
     */
    ListProductsResponse,

    /**
     * The ListProductsResponsePage model constructor.
     * @property {module:model/ListProductsResponsePage}
     */
    ListProductsResponsePage,

    /**
     * The ListReceiptsResponse model constructor.
     * @property {module:model/ListReceiptsResponse}
     */
    ListReceiptsResponse,

    /**
     * The ListReceiptsResponsePage model constructor.
     * @property {module:model/ListReceiptsResponsePage}
     */
    ListReceiptsResponsePage,

    /**
     * The ListReceivedDocumentCategoriesResponse model constructor.
     * @property {module:model/ListReceivedDocumentCategoriesResponse}
     */
    ListReceivedDocumentCategoriesResponse,

    /**
     * The ListReceivedDocumentsResponse model constructor.
     * @property {module:model/ListReceivedDocumentsResponse}
     */
    ListReceivedDocumentsResponse,

    /**
     * The ListReceivedDocumentsResponsePage model constructor.
     * @property {module:model/ListReceivedDocumentsResponsePage}
     */
    ListReceivedDocumentsResponsePage,

    /**
     * The ListRevenueCentersResponse model constructor.
     * @property {module:model/ListRevenueCentersResponse}
     */
    ListRevenueCentersResponse,

    /**
     * The ListSuppliersResponse model constructor.
     * @property {module:model/ListSuppliersResponse}
     */
    ListSuppliersResponse,

    /**
     * The ListSuppliersResponsePage model constructor.
     * @property {module:model/ListSuppliersResponsePage}
     */
    ListSuppliersResponsePage,

    /**
     * The ListTemplatesResponse model constructor.
     * @property {module:model/ListTemplatesResponse}
     */
    ListTemplatesResponse,

    /**
     * The ListUnitsOfMeasureResponse model constructor.
     * @property {module:model/ListUnitsOfMeasureResponse}
     */
    ListUnitsOfMeasureResponse,

    /**
     * The ListUserCompaniesResponse model constructor.
     * @property {module:model/ListUserCompaniesResponse}
     */
    ListUserCompaniesResponse,

    /**
     * The ListUserCompaniesResponseData model constructor.
     * @property {module:model/ListUserCompaniesResponseData}
     */
    ListUserCompaniesResponseData,

    /**
     * The ListVatTypesResponse model constructor.
     * @property {module:model/ListVatTypesResponse}
     */
    ListVatTypesResponse,

    /**
     * The ModifyArchiveDocumentRequest model constructor.
     * @property {module:model/ModifyArchiveDocumentRequest}
     */
    ModifyArchiveDocumentRequest,

    /**
     * The ModifyArchiveDocumentResponse model constructor.
     * @property {module:model/ModifyArchiveDocumentResponse}
     */
    ModifyArchiveDocumentResponse,

    /**
     * The ModifyCashbookEntryRequest model constructor.
     * @property {module:model/ModifyCashbookEntryRequest}
     */
    ModifyCashbookEntryRequest,

    /**
     * The ModifyCashbookEntryResponse model constructor.
     * @property {module:model/ModifyCashbookEntryResponse}
     */
    ModifyCashbookEntryResponse,

    /**
     * The ModifyClientRequest model constructor.
     * @property {module:model/ModifyClientRequest}
     */
    ModifyClientRequest,

    /**
     * The ModifyClientResponse model constructor.
     * @property {module:model/ModifyClientResponse}
     */
    ModifyClientResponse,

    /**
     * The ModifyF24Request model constructor.
     * @property {module:model/ModifyF24Request}
     */
    ModifyF24Request,

    /**
     * The ModifyF24Response model constructor.
     * @property {module:model/ModifyF24Response}
     */
    ModifyF24Response,

    /**
     * The ModifyIssuedDocumentRequest model constructor.
     * @property {module:model/ModifyIssuedDocumentRequest}
     */
    ModifyIssuedDocumentRequest,

    /**
     * The ModifyIssuedDocumentResponse model constructor.
     * @property {module:model/ModifyIssuedDocumentResponse}
     */
    ModifyIssuedDocumentResponse,

    /**
     * The ModifyPaymentAccountRequest model constructor.
     * @property {module:model/ModifyPaymentAccountRequest}
     */
    ModifyPaymentAccountRequest,

    /**
     * The ModifyPaymentAccountResponse model constructor.
     * @property {module:model/ModifyPaymentAccountResponse}
     */
    ModifyPaymentAccountResponse,

    /**
     * The ModifyPaymentMethodRequest model constructor.
     * @property {module:model/ModifyPaymentMethodRequest}
     */
    ModifyPaymentMethodRequest,

    /**
     * The ModifyPaymentMethodResponse model constructor.
     * @property {module:model/ModifyPaymentMethodResponse}
     */
    ModifyPaymentMethodResponse,

    /**
     * The ModifyProductRequest model constructor.
     * @property {module:model/ModifyProductRequest}
     */
    ModifyProductRequest,

    /**
     * The ModifyProductResponse model constructor.
     * @property {module:model/ModifyProductResponse}
     */
    ModifyProductResponse,

    /**
     * The ModifyReceiptRequest model constructor.
     * @property {module:model/ModifyReceiptRequest}
     */
    ModifyReceiptRequest,

    /**
     * The ModifyReceiptResponse model constructor.
     * @property {module:model/ModifyReceiptResponse}
     */
    ModifyReceiptResponse,

    /**
     * The ModifyReceivedDocumentRequest model constructor.
     * @property {module:model/ModifyReceivedDocumentRequest}
     */
    ModifyReceivedDocumentRequest,

    /**
     * The ModifyReceivedDocumentResponse model constructor.
     * @property {module:model/ModifyReceivedDocumentResponse}
     */
    ModifyReceivedDocumentResponse,

    /**
     * The ModifySupplierRequest model constructor.
     * @property {module:model/ModifySupplierRequest}
     */
    ModifySupplierRequest,

    /**
     * The ModifySupplierResponse model constructor.
     * @property {module:model/ModifySupplierResponse}
     */
    ModifySupplierResponse,

    /**
     * The MonthlyTotal model constructor.
     * @property {module:model/MonthlyTotal}
     */
    MonthlyTotal,

    /**
     * The Pagination model constructor.
     * @property {module:model/Pagination}
     */
    Pagination,

    /**
     * The PaymentAccount model constructor.
     * @property {module:model/PaymentAccount}
     */
    PaymentAccount,

    /**
     * The PaymentMethod model constructor.
     * @property {module:model/PaymentMethod}
     */
    PaymentMethod,

    /**
     * The PaymentMethodDetails model constructor.
     * @property {module:model/PaymentMethodDetails}
     */
    PaymentMethodDetails,

    /**
     * The PermissionLevel model constructor.
     * @property {module:model/PermissionLevel}
     */
    PermissionLevel,

    /**
     * The Permissions model constructor.
     * @property {module:model/Permissions}
     */
    Permissions,

    /**
     * The PermissionsFicIssuedDocumentsDetailed model constructor.
     * @property {module:model/PermissionsFicIssuedDocumentsDetailed}
     */
    PermissionsFicIssuedDocumentsDetailed,

    /**
     * The Product model constructor.
     * @property {module:model/Product}
     */
    Product,

    /**
     * The Receipt model constructor.
     * @property {module:model/Receipt}
     */
    Receipt,

    /**
     * The ReceiptItemsListItem model constructor.
     * @property {module:model/ReceiptItemsListItem}
     */
    ReceiptItemsListItem,

    /**
     * The ReceiptPreCreateInfo model constructor.
     * @property {module:model/ReceiptPreCreateInfo}
     */
    ReceiptPreCreateInfo,

    /**
     * The ReceiptType model constructor.
     * @property {module:model/ReceiptType}
     */
    ReceiptType,

    /**
     * The ReceivedDocument model constructor.
     * @property {module:model/ReceivedDocument}
     */
    ReceivedDocument,

    /**
     * The ReceivedDocumentEntity model constructor.
     * @property {module:model/ReceivedDocumentEntity}
     */
    ReceivedDocumentEntity,

    /**
     * The ReceivedDocumentInfo model constructor.
     * @property {module:model/ReceivedDocumentInfo}
     */
    ReceivedDocumentInfo,

    /**
     * The ReceivedDocumentInfoDefaultValues model constructor.
     * @property {module:model/ReceivedDocumentInfoDefaultValues}
     */
    ReceivedDocumentInfoDefaultValues,

    /**
     * The ReceivedDocumentInfoItemsDefaultValues model constructor.
     * @property {module:model/ReceivedDocumentInfoItemsDefaultValues}
     */
    ReceivedDocumentInfoItemsDefaultValues,

    /**
     * The ReceivedDocumentItemsList model constructor.
     * @property {module:model/ReceivedDocumentItemsList}
     */
    ReceivedDocumentItemsList,

    /**
     * The ReceivedDocumentPaymentTerms model constructor.
     * @property {module:model/ReceivedDocumentPaymentTerms}
     */
    ReceivedDocumentPaymentTerms,

    /**
     * The ReceivedDocumentPaymentsList model constructor.
     * @property {module:model/ReceivedDocumentPaymentsList}
     */
    ReceivedDocumentPaymentsList,

    /**
     * The ReceivedDocumentTotals model constructor.
     * @property {module:model/ReceivedDocumentTotals}
     */
    ReceivedDocumentTotals,

    /**
     * The ReceivedDocumentType model constructor.
     * @property {module:model/ReceivedDocumentType}
     */
    ReceivedDocumentType,

    /**
     * The ScheduleEmailRequest model constructor.
     * @property {module:model/ScheduleEmailRequest}
     */
    ScheduleEmailRequest,

    /**
     * The SendEInvoiceRequest model constructor.
     * @property {module:model/SendEInvoiceRequest}
     */
    SendEInvoiceRequest,

    /**
     * The SendEInvoiceRequestData model constructor.
     * @property {module:model/SendEInvoiceRequestData}
     */
    SendEInvoiceRequestData,

    /**
     * The SendEInvoiceResponse model constructor.
     * @property {module:model/SendEInvoiceResponse}
     */
    SendEInvoiceResponse,

    /**
     * The SendEInvoiceResponseData model constructor.
     * @property {module:model/SendEInvoiceResponseData}
     */
    SendEInvoiceResponseData,

    /**
     * The Supplier model constructor.
     * @property {module:model/Supplier}
     */
    Supplier,

    /**
     * The UploadArchiveAttachmentResponse model constructor.
     * @property {module:model/UploadArchiveAttachmentResponse}
     */
    UploadArchiveAttachmentResponse,

    /**
     * The UploadF24AttachmentResponse model constructor.
     * @property {module:model/UploadF24AttachmentResponse}
     */
    UploadF24AttachmentResponse,

    /**
     * The UploadIssuedDocumentAttachmentResponse model constructor.
     * @property {module:model/UploadIssuedDocumentAttachmentResponse}
     */
    UploadIssuedDocumentAttachmentResponse,

    /**
     * The UploadIssuedDocumentAttachmentResponseData model constructor.
     * @property {module:model/UploadIssuedDocumentAttachmentResponseData}
     */
    UploadIssuedDocumentAttachmentResponseData,

    /**
     * The UploadReceivedDocumentAttachmentResponse model constructor.
     * @property {module:model/UploadReceivedDocumentAttachmentResponse}
     */
    UploadReceivedDocumentAttachmentResponse,

    /**
     * The UploadReceivedDocumentAttachmentResponseData model constructor.
     * @property {module:model/UploadReceivedDocumentAttachmentResponseData}
     */
    UploadReceivedDocumentAttachmentResponseData,

    /**
     * The User model constructor.
     * @property {module:model/User}
     */
    User,

    /**
     * The VatType model constructor.
     * @property {module:model/VatType}
     */
    VatType,

    /**
     * The VerifyEInvoiceXmlErrorResponse model constructor.
     * @property {module:model/VerifyEInvoiceXmlErrorResponse}
     */
    VerifyEInvoiceXmlErrorResponse,

    /**
     * The VerifyEInvoiceXmlErrorResponseError model constructor.
     * @property {module:model/VerifyEInvoiceXmlErrorResponseError}
     */
    VerifyEInvoiceXmlErrorResponseError,

    /**
     * The VerifyEInvoiceXmlErrorResponseExtra model constructor.
     * @property {module:model/VerifyEInvoiceXmlErrorResponseExtra}
     */
    VerifyEInvoiceXmlErrorResponseExtra,

    /**
     * The VerifyEInvoiceXmlResponse model constructor.
     * @property {module:model/VerifyEInvoiceXmlResponse}
     */
    VerifyEInvoiceXmlResponse,

    /**
     * The VerifyEInvoiceXmlSuccessResponse model constructor.
     * @property {module:model/VerifyEInvoiceXmlSuccessResponse}
     */
    VerifyEInvoiceXmlSuccessResponse,

    /**
     * The VerifyEInvoiceXmlSuccessResponseData model constructor.
     * @property {module:model/VerifyEInvoiceXmlSuccessResponseData}
     */
    VerifyEInvoiceXmlSuccessResponseData,

    /**
    * The ArchiveApi service constructor.
    * @property {module:api/ArchiveApi}
    */
    ArchiveApi,

    /**
    * The CashbookApi service constructor.
    * @property {module:api/CashbookApi}
    */
    CashbookApi,

    /**
    * The ClientsApi service constructor.
    * @property {module:api/ClientsApi}
    */
    ClientsApi,

    /**
    * The CompaniesApi service constructor.
    * @property {module:api/CompaniesApi}
    */
    CompaniesApi,

    /**
    * The InfoApi service constructor.
    * @property {module:api/InfoApi}
    */
    InfoApi,

    /**
    * The IssuedDocumentsApi service constructor.
    * @property {module:api/IssuedDocumentsApi}
    */
    IssuedDocumentsApi,

    /**
    * The IssuedEInvoicesApi service constructor.
    * @property {module:api/IssuedEInvoicesApi}
    */
    IssuedEInvoicesApi,

    /**
    * The ProductsApi service constructor.
    * @property {module:api/ProductsApi}
    */
    ProductsApi,

    /**
    * The ReceiptsApi service constructor.
    * @property {module:api/ReceiptsApi}
    */
    ReceiptsApi,

    /**
    * The ReceivedDocumentsApi service constructor.
    * @property {module:api/ReceivedDocumentsApi}
    */
    ReceivedDocumentsApi,

    /**
    * The SettingsApi service constructor.
    * @property {module:api/SettingsApi}
    */
    SettingsApi,

    /**
    * The SuppliersApi service constructor.
    * @property {module:api/SuppliersApi}
    */
    SuppliersApi,

    /**
    * The TaxesApi service constructor.
    * @property {module:api/TaxesApi}
    */
    TaxesApi,

    /**
    * The UserApi service constructor.
    * @property {module:api/UserApi}
    */
    UserApi
};
