/**
 * Fatture in Cloud API v2 - API Reference
 * Connect your software with Fatture in Cloud, the invoicing platform chosen by more than 400.000 businesses in Italy.   The Fatture in Cloud API is based on REST, and makes possible to interact with the user related data prior authorization via OAuth2 protocol.  For more information, please visit https://www.fattureincloud.it.
 *
 * The version of the OpenAPI document: 2.0.1
 * Contact: info@fattureincloud.it
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The PaymentAccount model module.
 * @module FattureInCloud/model/PaymentAccount
 * @version 2.0.1
 */
class PaymentAccount {
    /**
     * Constructs a new <code>PaymentAccount</code>.
     * Payment account.
     * @alias module:FattureInCloud/model/PaymentAccount
     * @param name {String} Payment account name.
     */
    constructor(name) { 
        
        PaymentAccount.initialize(this, name);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, name) { 
        obj['name'] = name;
    }

    /**
     * Constructs a <code>PaymentAccount</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:FattureInCloud/model/PaymentAccount} obj Optional instance to populate.
     * @return {module:FattureInCloud/model/PaymentAccount} The populated <code>PaymentAccount</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PaymentAccount();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
            if (data.hasOwnProperty('iban')) {
                obj['iban'] = ApiClient.convertToType(data['iban'], 'String');
            }
            if (data.hasOwnProperty('sia')) {
                obj['sia'] = ApiClient.convertToType(data['sia'], 'String');
            }
            if (data.hasOwnProperty('cuc')) {
                obj['cuc'] = ApiClient.convertToType(data['cuc'], 'String');
            }
            if (data.hasOwnProperty('virtual')) {
                obj['virtual'] = ApiClient.convertToType(data['virtual'], 'Boolean');
            }
        }
        return obj;
    }


}

/**
 * Unique identifier
 * @member {Number} id
 */
PaymentAccount.prototype['id'] = undefined;

/**
 * Payment account name.
 * @member {String} name
 */
PaymentAccount.prototype['name'] = undefined;

/**
 * Payment account type.
 * @member {module:FattureInCloud/model/PaymentAccount.TypeEnum} type
 * @default 'standard'
 */
PaymentAccount.prototype['type'] = 'standard';

/**
 * Payment account iban.
 * @member {String} iban
 */
PaymentAccount.prototype['iban'] = undefined;

/**
 * Payment account sia.
 * @member {String} sia
 */
PaymentAccount.prototype['sia'] = undefined;

/**
 * Payment account cuc.
 * @member {String} cuc
 */
PaymentAccount.prototype['cuc'] = undefined;

/**
 * Determine if the payment method is virtual.
 * @member {Boolean} virtual
 */
PaymentAccount.prototype['virtual'] = undefined;





/**
 * Allowed values for the <code>type</code> property.
 * @enum {String}
 * @readonly
 */
PaymentAccount['TypeEnum'] = {

    /**
     * value: "standard"
     * @const
     */
    "standard": "standard",

    /**
     * value: "bank"
     * @const
     */
    "bank": "bank"
};



export default PaymentAccount;

